version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    directories:
      - "/"
    schedule:
      interval: "weekly"
    groups:
      k8s:
        patterns:
          - "k8s.io*"
          - "sigs.k8s.io*"
      all-go-mod-patch-and-minor:
        patterns: [ "*" ]
        update-types: [ "patch", "minor" ]

  - package-ecosystem: "gomod"
    directory: "/tools"
    schedule:
      interval: "weekly"
    groups:
      all-go-mod-patch-and-minor:
        patterns: [ "*" ]
        update-types: [ "patch", "minor" ]

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every week
      interval: "weekly"
