run:
  timeout: 5m
  skip-dirs:
    - third-party

linters:
  disable-all: true
  enable:
  - errcheck
  - goconst
  - gocritic
  - goimports
  - gosimple
  - govet
  - ineffassign
  - nolintlint
  - prealloc
  - staticcheck
  - stylecheck
  - typecheck
  - unparam
  - unused
  - whitespace

linters-settings:
  goimports:
    local-prefixes: sigs.k8s.io/kubefed
