name: Build and Test

on:
  pull_request:
    types: [opened, reopened, edited, synchronize, labeled]
  push:
    tags:
      - "v*"
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v4
        with:
          go-version-file: go.mod

      - name: Run tests
        run: |
          ./hack/verify-docfiles.sh && echo "Skipping build - only doc files have changed!" || \
            DOWNLOAD_BINARIES=y bash -x ./scripts/pre-commit.sh
