name: release-please-main

permissions:
  contents: write
  pull-requests: write
  actions: write

on:
  workflow_dispatch: {}
  push:
    branches:
      # (todo): migrate to main
      - master

defaults:
  run:
    shell: bash

jobs:
  release-please:
    runs-on:
    - ubuntu-latest

    steps:
      - uses: googleapis/release-please-action@v4
        id: release-please
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json
