name: Test and Push

on:
  push:
    tags:
      - "v*"
    branches:
      - "master"

jobs:
  push:
    runs-on: ubuntu-latest

    permissions:
      packages: write

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v4
        with:
          go-version-file: go.mod

      - name: Run tests
        run: DOWNLOAD_BINARIES=y bash -x ./scripts/pre-commit.sh

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Docker images
        run: make push
